apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-project-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-project
  template:
    metadata:
      labels:
        app: reddit-project
    spec:
      containers:
        - name: reddit-container
          image: yatingambhir/reddit-clone:15
          resources:
            limits:
              cpu: "1"
            requests:
              cpu: "500m"
          ports:
            - containerPort: 3000
